const CAKE_ORDERED = 'CAKE_ORDERED';
const CAKE_RESTOCKED = 'CAKE_RESTOCK';
const CS_STUDENT_REMOVED = 'STUDENT_REMOVED';
const ICECREAM_ORDERED = 'ICECREAM_ORDERED';
const ICECREAM_RESTOCKED = 'ICECREAM_RESTOCKED';
const STREET_UPDATED = "STREET_UPDATED";

module.exports = { CAKE_ORDERED, CS_STUDENT_REMOVED, CAKE_RESTOCKED, ICECREAM_ORDERED, ICECREAM_RESTOCKED, STREET_UPDATED};